### Variables
@url = http://localhost:8080/api

### get employees
GET {{url}}/users

### create employees
POST {{url}}/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@mail.com"
}

### edit employee
PUT {{url}}/users/a664051a-f598-4803-92d6-2e890ade12cb
Content-Type: application/json

{
  "firstName": "Johnny",
  "lastName": "Doe",
  "email": "john.doe@mail.com"
}

### delete employee
DELETE {{url}}/users/a664051a-f598-4803-92d6-2e890ade12cb

### get locations
GET {{url}}/locations

### create location
POST {{url}}/locations
Content-Type: application/json

{
  "name": "BSO Test"
}

### edit location
PUT {{url}}/locations/5f5b5c65-4d8c-4418-b309-3c4eb5099615
Content-Type: application/json

{
  "name": "BSO Test 1"
}

### delete location
DELETE {{url}}/locations/5f5b5c65-4d8c-4418-b309-3c4eb5099615

### get planning
GET {{url}}/planning

### create planning
POST {{url}}/planning
Content-Type: application/json

{
  "year": 2025,
  "month": 11,
  "label": "Planning 11/2025"
}

### delete planning
DELETE {{url}}/planning/c3ad16f7-8334-454f-9889-dc7fa044701e

### create child
POST {{url}}/children
Content-Type: application/json

{
  "firstName": "Mirhte",
  "lastName": "Doe"
}

### import children
POST {{url}}/children/import
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="children.csv"

< /Users/fabrizzio.maya-lopez/workspace/personal/docs/Kinder Centrum Doen.csv
--WebAppBoundary--

